### PR TITLE
update a field in json

### PR DESCRIPTION
**Pull request by daisyden**
We'd like to remove an optional filed, could you please help to update the website?

### CODE REVIEW

**Comment by daisyden** [comment]
@codyaustun Can we remove the cost information?

**Comment by bignamehyp** [comment]
Is Resnet56 for imagenet a new model, or a typo of resnet50? There was a resnet56 model for cifar10, but not for imagenet.

**Comment by daisyden** [comment]
@bignamehyp We created a ResNet56 according to ImageNet ResNet50.

**Comment by codyaustun** [comment]
@bignamehyp ResNet56 isn't a typo. I asked about this in [#25](https://github.com/stanford-futuredata/dawn-bench-entries/pull/25). It is probably better to continue the discussion there, but I agree it isn't clear what ResNet56 actually means. In [
Deep Residual Learning for Image Recognition](https://arxiv.org/abs/1512.03385), ResNet56 is a model for CIFAR10. Looking at the [prototxt](https://github.com/intel/caffe/blob/7e45219234268dbeff38bcfc87cf460416365e21/models/intel_optimized_models/multinode/resnet_56_128_nodes_4k_batch/train_val.prototxt#L12), @daisyden made a model that works for ImageNet.

**Pull request merged**
