### PR TITLE
resnet 50 || imagenet || fast.ai + students

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by brettkoonce** [comment]
superseded by #35

**Comment by deepakn94** [comment]
@brettkoonce, out of curiosity, what were the differences between the two submissions?

**Comment by brettkoonce** [comment]
@deepakn94 some parameter tuning, a more aggressive learning schedule, and about an hour of gpu time 😄

**Comment by deepakn94** [comment]
I see. What parameters -- the batch size?

**Comment by brettkoonce** [comment]
@deepakn94 @jph00 can explain better!

**Comment by jph00** [comment]
Details will be in the post / paper which we'll release once the result is one the leaderboard, but the short answer is the key difference between the previous entry and this is we changed the data_scales param from (224,288) to (128,224,288) and adjusted the epoch phase mappings appropriately, which sped up the initial epochs.

**Pull request closed without merging**
