### PR TITLE
Update Cloud TPU results with new Top1 / Top5 accuracy numbers

### PR DESCRIPTION
**Pull request by frankchn**
The Stanford DAWNBench team recently discovered a bug in our benchmark script where we used a eval_batch_size of 1024 rather than 100, which resulted in us discarding about 800 images at the end of the evaluation dataset. 

We have re-run the saved checkpoints of our submission using the new batch size of 1000 to make sure that we are including all 50,000 images. In our run, there is no difference in the epoch (81) in which we achieved 93% Top-5 accuracy. Top 5 accuracy at the 81st epoch decreased by 0.02% to 93.01%, while Top 1 accuracy increased by 0.26% to 76.13%.

Thanks to @ddkang and the rest of the DAWNBench team for catching the error!

### CODE REVIEW

**Comment by codyaustun** [comment]
Looks good to me

**Comment by deepakn94** [comment]
Looks good to me too. Shouldn't the other TPU entries be updated too?

**Comment by frankchn** [comment]
@deepakn94 Yes, the other runs are done by other folks on the team and I've informed them of the error and they will create separate PRs for those.

**Comment by ddkang** [comment]
Looks good, thanks! Please let us know when the rest of the entries are fixed.

**Pull request merged**
