### PR TITLE
wideresnet || cifar10 || fast.ai + students

### PR DESCRIPTION
**Pull request by binga**
Training the wideresnet on CIFAR10 on Google Colaboratory.

### CODE REVIEW

**Comment by brettkoonce** [comment]
🎉

**Comment by codyaustun** [comment]
@binga I am not familiar with Google Colaboratory, and I am concerned that the pricing of these machines is too ephemeral to be included in DAWNBench. Is this based on a free tier or free trial model? Similar to spot and preemptible instances, if prices and performance can change dramatically, results aren't reproducible or reliable.

**Comment by brettkoonce** [comment]
No it's not a free trial or ephemeral in any way. It's free for anyone with no limitations, other than that your session must be complete within 12 hours. You can use as many sessions as you like, as often as you like. The price and performance are fixed and do not change in any way.

**Comment by binga** [comment]
@codyaustun The FAQs of the Google Colaboratory Service mentioning the details about the price are available here: https://research.google.com/colaboratory/faq.html
When you run a notebook on Colab, a 16GB RAM VM is provisioned with a 16GB K80 GPU which is free to use within a 12 hour window after which the instance terminates. As long as the jobs you run are within the 12 hour window, you are free to use the service any number of times.

**Comment by codyaustun** [comment]
@binga We can't accept this submission. We are only considering commercial platforms where the cost reflects what an organization would get at scale and in a commercial setting (with terms of service, SLAs, etc). Colaboratory is described as "a Google research project created to help disseminate machine learning education and research." It sounds like an awesome initiative but doesn't fit the scope of the current benchmark.

**Comment by codyaustun** [comment]
Also, thanks for making this submission! I was glad to learn that free services like this exist. I will try to share Google Colaboratory widely!

**Comment by jph00** [comment]
@codyaustun I very much empathize that you've found yourself in a situation where someone has found a way to win your competition, but not in a way you expected - and that it "doesn't fit the scope of the current benchmark". Back when I was the President and Chief Scientist of Kaggle I saw this happen many times - highly creative data scientists would find brilliant and surprising ways to win competitions, whilst meeting the rules we had set down. For instance, Arvind Narayanan (then a student, but now a prominent professor at Princeton) managed to win a competition by figuring out a way to actually deanonymize the competition dataset and look up the answers directly! In this case, and every one like it, we always supported the data scientists that had found a way to win within the written rules, and respected the hard work and creativity they put in to their solution. Their entry was accepted and rewarded.

The rules of the competition at the time the entry in this PR was made did not mention a constraint of "commercial platforms where the cost reflects what an organization would get at scale and in a commercial setting". Changing the rules the day before the end of the competition is a pretty rough thing to do to those people who have dedicated significant time to contributing to your project. In this case, for instance (whilst I know @binga would never say a word of complaint himself) I can tell you that he's traveled from India to SF to do this course, and spent significant time and effort here getting this to train successfully on Colab so as to make this entry.

I wonder if you might consider changing the rules for your next competition, but accepting this entry for this competition. I think it would help to set up this competition series as a trusted project for the future, would be excellent publicity for an important resource that Google has kindly provided to the community, and would be fair recognition for those who worked hard to complete this entry.

(Finally, I note that your white paper says that you are looking for order of magnitude changes. This is only going to happen if you accept some creative and surprising solutions, and that competitors know that such solutions will be accepted in the future as long as they meet the rules.)

**Comment by codyaustun** [comment]
@binga @jph00 we are going to discuss this further, but I can't guarantee that the decision will change. Please be patient as we review this case in more detail.

**Comment by brettkoonce** [comment]
Cool!

**Comment by binga** [comment]
@codyaustun thank you. We look forward to the final result.

**Comment by codyaustun** [comment]
@binga @jph00 We discussed this as a team and decided that we can't accept this submission for cost. The lack of measured service and billing doesn't fit the definition of "cloud" computing, where hardware or software is sold as a utility, and the platform's focus on "machine learning education and research" restricts commercial entities, thus not making it "public".

However, we can include this submission per time. If you remove the `costPerHour` field, we'll merge this.

Thanks!

**Comment by jph00** [comment]
There is no restriction on Google Colab regarding commercial entities, and no commonly accepted usage of the term "cloud" that does not include free services. For instance, Stanford University (the home of this project) describes box.com as "[free cloud storage](https://it-humsci.stanford.edu/services/cloud-storage)". Google (sponsors of this project) describe their free Google Drive product as "cloud" storage on its home page.

These are rather creative definitions of "public" and "cloud", to say the least.

**Comment by jph00** [comment]
To clarify: we accept the decision, which is yours to make. However, personally, I'd rather it had been handled and communicated differently.

Nonetheless, many thanks for all the hard work in running this project.

**Comment by codyaustun** [comment]
Thanks, @jph00. I'll merge this in once `costPerHour` is removed, and we will be clearer next time.

**Comment by jph00** [comment]
You can just close this PR - we were only wanting to enter the cost competition here.

**Pull request closed without merging**
