### PR TITLE
Resnet50 || ImageNet Training || ZTE AI Platform

### PR DESCRIPTION
**Pull request by Veitch-Li**
Resnet 50 Training on Imagenet to 93% Top-5 accuracy on ZTE AI Platform using 2 nodes (8*V100 for each node).

The framework is TensorFlow v1.12.0.
Please let me know if you have any questions!

### CODE REVIEW

**Comment by Veitch-Li** [comment]
> Resnet 50 Training on Imagenet to 93% Top-5 accuracy on ZTE AI Platform using 2 nodes (8*V100 for each node).
> 
> The framework is TensorFlow v1.12.0.
> Please let me know if you have any questions!

**Comment by Veitch-Li** [comment]
@codyaustun can you help me to process this pull request. Thanks!

**Comment by codyaustun** [comment]
@Veitch-Li I have been traveling, but I should be able to take a look at this tonight. Thanks for your patience.

**Comment by codyaustun** [comment]
@Veitch-Li it doesn't look like this is in the top 5 submissions for any leaderboard, so it doesn't qualify under the rolling submission rules. Please see [the DAWNBench rolling submissions announcement](https://dawn.cs.stanford.edu/2018/07/25/dawnbench_rolling/). Let me know if you have any questions.

**Comment by Veitch-Li** [comment]
@codyaustun Thanks for the reply.I am very sorry for not seeing the announcement before.
We decide to use our another hardware with 8 nodes (8*P100 for each node) and may reduce the training time.I will submit the new result tomorrow.

**Comment by Veitch-Li** [comment]
@codyaustun I run my code on another hardware using 8 nodes (8*P100 for each node).the training time has been reduced to 23 minutes.it look like this is in the top 5 submissions for imagenet train time leaderboard.I have submitted a new result.please take another look.Thanks.please let me know if you have any questions.

**Comment by codyaustun** [comment]
Looks good to me. Thanks for the update!

**Pull request merged**
