### PR TITLE
ResNet-50 || ImageNet Training cost || AlibabaCloud

### PR DESCRIPTION
**Pull request by listenlink**
Hi, this is a ResNet-50 config trained on an AlibabaCloud ecs.gn6e-c12g1.24xlarge (an-8-Tesla-V100 GPUs instance) 

The model is trained with Tensorflow 2.1 and AIACC-Training 1.3. It is a significant update as it only runs on a single machine to hit the best cost record ($7.42)  with a very short training time (0.36 hour).

kindly Note:
* AIACC-Training is a highly-optimized distributed training framework that horovod api compatible developed by AlibabaCloud. The cloud image that AIACC-Training included can be found at https://market.aliyun.com/products/57742013/cmjj032323.html?#product-contain

* The price info of instance `ecs.gn6e-c12g1.24xlarge` can be found as below. It is 142.12RMB($20.60) per hour
https://ecs-buy.aliyun.com/wizard?spm=5176.8300896.676846.price13.11c06539pk5Bel#/postpay/cn-zhangjiakou?zoneId=cn-shanghai-f&instanceType=ecs.gn6e-c12g1.24xlarge

The whole training scripts will be opensource later in a way that reproducible. Please let me know for any questions. Thanks a lot.

### CODE REVIEW

**Comment by codyaustun** [comment]
@listenlink is there a page that doesn't require you to login that shows the price for a `ecs.gn6e-c12g1.24xlarge`? The link you sent requires me to sign in. If not, can you send a screenshot of the webpage with the price for the instance?

**Comment by listenlink** [comment]
@codyaustun The screenshot of the website with price as below, thanks!
image

**Comment by codyaustun** [comment]
Thanks! Looks good to me now. Please update when you have open-sourced the code.

**Comment by ppope** [comment]
@listenlink any update on when the training scripts will be released?

**Pull request merged**
