### PR TITLE
fix name resnet152->resnet50

### PR DESCRIPTION
**Pull request by yaroslavvb**

### CODE REVIEW

**Comment by codyaustun** [comment]
@yaroslavvb by any chance, do you have a log file like [ppwwyyxx's pull request](https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/ImageNet/train/ppwwyyxx_resnet152_8P100-DGX1_tensorpack.json#L10)?

**Comment by yaroslavvb** [comment]
here are all the logs/event files from training, seemed a bit too large to put on github: https://www.dropbox.com/sh/sjllty4sdlbr5qc/AAAGSEvTUB1g5NbYvIEehx4Ya?dl=0

PS, tensorboard with all the runs I did is here:
http://54.197.6.125:6006/

Basically that was the first run (resnet.b512.baseline), then I tried again (resnet.b512.baseline2) for a few hours and checked that accuracy tracked the first one pretty closely, to make sure it wasn't a fluke

**Comment by yaroslavvb** [comment]
I considered uploading them, but how do I get things into `https://github.com/stanford-futuredata/dawn-bench-entries/files/` location? There's no `files` folder in the repo. Is it the "upload file" button? That needs extra access
screenshot 2018-02-14 09 08 22

**Comment by codyaustun** [comment]
@yaroslavvb just attach the file to a comment and update the pull request with the URL GitHub generates. For example, here is the log file from your dropbox folder [log.log](https://github.com/stanford-futuredata/dawn-bench-entries/files/1725379/log.log). You could also just use that link. [Here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) is more information on file attachments.

**Comment by yaroslavvb** [comment]
Done. Also added events file which has more info and can be viewed with TensorBoard. Events file is 25.5MB and the github limit seems to be 25 MB so I added event log file as a link to dropbox upload.

**Comment by codyaustun** [comment]
@yaroslavvb can you move the 'logFilename' and 'eventsFilename' fields into 'misc'? Aside from that it looks good to me.

**Comment by yaroslavvb** [comment]
done

**Pull request merged**
